name: Install tests

on: [push]

jobs:
  macos:
    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npx cheerp test/hello.cpp -o test/hello.js
      - run: node test/hello.js > test/hello.out
      - run: diff test/hello.out test/hello.expected
