name: Install tests

on: [push]

jobs:
  macos:
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x, 20.x]
        os: [macos-latest, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install -f
      - run: npx cheerp test/hello.cpp -o test/hello.js
      - run: node test/hello.js > test/hello.out
      - run: diff test/hello.out test/hello.expected
